services:

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    restart: always

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
        reservations:
          cpus: '0.5'
          memory: 256m

    ports:
      - "8080:80"

    environment:
      PUID: 1000
      PGID: 10

    volumes:
      - type: bind
        source: /volume1/docker/php/www
        target: /var/www/html/

# with docker compose 2.30
# check with "docker compose version"
#    post_start:
#      - command: ["/bin/bash", "-c", "chmod -R 755 /var/www/html/"]
