services:

  db:
    image: mysql:oraclelinux9
    restart: always

    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1gb
        reservations:
          cpus: '2'
          memory: 512m

    ports:
      - "3306:3306"

    environment:
      PUID: 1000
      PGID: 10
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password

    secrets:
       - db_root_password

    volumes:
      - type: bind
        source: /volume1/docker/mysql/data
        target: /var/lib/mysql

secrets:
   db_root_password:
     file: /volume1/docker/mysql/secret/db_root_password.txt
